
config = {
    'runner': 'episode',
    'mac': 'basic_mac',
    'env': 'mv_ctn',
    'episode_limit': 180,
    'n_agents': 25, 'highway_length': 250,
    'obs_dim': 38,
    'lanes': 4,
    'acc_step': 2, 'max_hv_speed': 15, 'max_av_speed': 20,
    'w_speed': 10.0, 'w_steady': 1.0, 'w_keep': 2.0, 'w_intention': 30.0, 'w_p_crash': 50.0, 'w_pla': 8.0,
    'w_sigma': 60, 'w_zeta': 1,
    'w_safe_gap': 5.0,
    'test_episodes': 1000,
    'del_thres': 1,
    'env_args': {
        'continuing_episode': False,
        'difficulty': '7',
        'game_version': None,
        'map_name': '3m',
        'move_amount': 2,
        'obs_last_action': False,
        'reward_scale': True,
        'reward_scale_rate': 20,
        'reward_sparse': False,
        'state_last_action': True,
        'state_timestep_number': False,
        'heuristic_rest': False,
        'debug': False,
    },
    'n_actions': 9, 'state_shape': 48,
    'batch_size_run': 1, 'test_nepisode': 32, 'test_interval': 10000,
    'test_greedy': True, 'log_interval': 10000, 'runner_log_interval': 10000,
    'learner_log_interval': 10000, 't_max': 5050000, 'use_cuda': True, 'GPU': 'cuda:0',
    'buffer_cpu_only': True, 'is_save_buffer': False, 'save_buffer_size': 10000,
    'save_buffer_interval': 1000,
    'is_batch_rl': False, 'load_buffer_id': 0, 'save_buffer_id': 0,
    'is_from_start': True, 'num_circle': 1,
    # 'burn_in_period': 32,
    'burn_in_period': 4,
    'use_tensorboard': True,
    'save_model': False, 'save_model_interval': 500000, 'checkpoint_path': '', 'evaluate': False,
    'load_step': 0, 'save_replay': False, 'local_results_path': 'results', 'gamma': 0.99,
    # 'batch_size': 32,
    'batch_size': 4,
    'buffer_size': 5000, 'lr': 0.0005, 'critic_lr': 0.0005, 'optim_alpha': 0.99,
    'optim_eps': 1e-05, 'grad_norm_clip': 10, 'agent': 'rnn', 'rnn_hidden_dim': 64, 'obs_agent_id': False,
    'obs_last_action': True, 'repeat_id': 1, 'label': 'default_label', 'round': 3,
    'action_selector': 'epsilon_greedy', 'epsilon_start': 1.0, 'epsilon_finish': 0.05,
    'epsilon_anneal_time': 50000, 'target_update_interval': 200, 'agent_output_type': 'q',
    'learner': 'QMIX', 'double_q': True, 'mixer': 'qmix', 'mixing_embed_dim': 32,
    'hypernet_layers': 2, 'hypernet_embed': 64, 'on_policy_batch': 16, 'predict_epoch': 25,
    'predict_net_dim': 128, 'beta1': 0.01, 'beta2': 0.02, 'ifaver': True, 'ifon_sample': False,
    'ifaddobs': True, 'alpha': 0.3, 'name': 'topo_enhance', 'seed': 389008264
}
